package com.cordys.coe.ac.scriptconnector;

import com.eibus.localization.message.Message;
import com.eibus.localization.message.MessageSet;

/**
 * This code is generated by running com.cordys.coe.cep.wizards.localization.CoEMessageGenerator.
 */
public class LogMessages
{
	/**
	 * Holds the definition of the message set.
	 */
	public static final MessageSet MESSAGE_SET = MessageSet.getMessageSet("com.cordys.coe.ac.scriptconnector.LogMessages");

	/**
	 * Holds the definition of the message with ID UnableToOpenConnector.
	 * Message text:
	 * Unable to open the connector object.
	 */
	public static final Message UNABLE_TO_OPEN_CONNECTOR = MESSAGE_SET.getMessage("UnableToOpenConnector");
	/**
	 * Holds the definition of the message with ID TransactionFailed.
	 * Message text:
	 * ScriptConnector transaction failed: {0}
	 */
	public static final Message TRANSACTION_FAILED = MESSAGE_SET.getMessage("TransactionFailed");
	/**
	 * Holds the definition of the message with ID CONNECTOR_INITIALIZATION_FAILED.
	 * Message text:
	 * Connector initialization failed.
	 */
	public static final Message CONNECTOR_INITIALIZATION_FAILED = MESSAGE_SET.getMessage("CONNECTOR_INITIALIZATION_FAILED");

}